<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="FooTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2017-05-15T23:09:04" hostname="DESKTOP-0010" time="0.032">
  <properties/>
  <testcase name="constructorCalled_innerObjectNull_ThrowsException" classname="FooTest" time="0.03"/>
  <testcase name="constructorCalled_bothParamsNull_ThrowsException" classname="FooTest" time="0.0"/>
  <testcase name="constructorCalled_ValidParams_FooCreated" classname="FooTest" time="0.002"/>
  <testcase name="constructorCalled_innerObjectNullField_ThrowsException" classname="FooTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[May 16, 2017 9:09:04 AM net.sf.oval.internal.Log info
INFO: Instantiated
]]></system-err>
</testsuite>
