<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="FooTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2017-05-12T06:51:22" hostname="DESKTOP-0010" time="0.041">
  <properties/>
  <testcase name="constructorCalled_innerObjectNull_ThrowsException" classname="FooTest" time="0.038"/>
  <testcase name="constructorCalled_bothParamsNull_ThrowsException" classname="FooTest" time="0.001"/>
  <testcase name="constructorCalled_ValidParams_FooCreated" classname="FooTest" time="0.002"/>
  <testcase name="constructorCalled_innerObjectNullField_ThrowsException" classname="FooTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[May 12, 2017 4:51:22 PM net.sf.oval.internal.Log info
INFO: Instantiated
]]></system-err>
</testsuite>
